### ISSUE TITLE
Practica #1 Validación de propuesta de valor 

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-mitte#2]
[Practica 1_Validacion de la propuesta de valor.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-mitte/files/6130644/Practica.1_Validacion.de.la.propuesta.de.valor.pdf)

**Comment by dulce-blm** [comment]
El trabajo cumple con todos los requisitos. Calificación 20 puntos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
