### ISSUE TITLE
Practica #2 Costos 

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-mitte#3]
[Reporte de practica #2 Costos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-mitte/files/6136158/Reporte.de.practica.2.Costos.pdf)
[Costos MiTTE.xlsx](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-mitte/files/6135981/Costos.MiTTE.xlsx)

**Comment by dulce-blm** [comment]
El trabajo cumple con todos los requisitos. Calificación 20 puntos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
